# Generated by Django 4.0.5 on 2022-10-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('insta_url', models.URLField(blank=True, null=True)),
                ('linked_in_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
